name: Deploy to QA (Node.js)

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-qanode
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: qanode
      build_env: qa
    secrets: inherit
