name: Deploy to QA (Node.js)

on:
  workflow_dispatch:

concurrency:
  group: deploy-qa-node
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: qa-node
      build_env: qa
    secrets: inherit
